### ISSUE TITLE
Unrecognized function or variable 'kcircle'.

### ISSUE THREAD

**Issue by yisinyang** [TarekSaati/LearnToNavigate#3]
Sorry, when I executed the program code, I found some errors in the "main".m file. At present, I encountered the problem of "kcircle" first. It told me that there is no definition. I am wondering if there is any part of the program code that is not provided? Thank you.

**Comment by TarekSaati** [comment]
Hi Yisin!
Your feedback is appreciated.
Actually yes.. "kcircle.m" was missing and I uploaded it.
You can refer to my article for more intuition on the path planning and obstacle avoidance method:
https://link.springer.com/article/10.3103/S014641162301008X
Your comments are welcomed.
